node('production') {
    env.TAG_WEB_IMAGE = "offlogs-production-web"
    env.FRONTEND_WEB_IMAGE = "offlogs-production-web"

    stage('Checkout') {
        checkout scm
        sh 'ls -sh'
    }
    
    stage('Build Web image') {
        sh 'docker build --tag=$TAG_WEB_IMAGE --file="devops/publish/web/Dockerfile" .'
    }
    
    stage('Build Frontend image') {
            sh 'docker build --tag=$FRONTEND_WEB_IMAGE --file="devops/publish/front/Dockerfile" .'
        }
    
    stage('Run images') {
        sh 'docker run -d $TAG_WEB_IMAGE'
        sh 'docker run -d $FRONTEND_WEB_IMAGE'
    }
}
