//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OffLogs.Business.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RG {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RG() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("OffLogs.Business.Resources.RG", typeof(RG).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Error_IncorrectConstantValue {
            get {
                return ResourceManager.GetString("Error_IncorrectConstantValue", resourceCulture);
            }
        }
        
        internal static string Error_FieldMayContainOnlyPositiveDigits {
            get {
                return ResourceManager.GetString("Error_FieldMayContainOnlyPositiveDigits", resourceCulture);
            }
        }
        
        internal static string Error_ArrayStringIsTooLong {
            get {
                return ResourceManager.GetString("Error_ArrayStringIsTooLong", resourceCulture);
            }
        }
        
        internal static string Error_ArrayIsTooBig {
            get {
                return ResourceManager.GetString("Error_ArrayIsTooBig", resourceCulture);
            }
        }
        
        internal static string Error_ArrayStringIsTooShort {
            get {
                return ResourceManager.GetString("Error_ArrayStringIsTooShort", resourceCulture);
            }
        }
        
        internal static string Error_ArrayStringCanNotBeNull {
            get {
                return ResourceManager.GetString("Error_ArrayStringCanNotBeNull", resourceCulture);
            }
        }
        
        internal static string Error_FieldContainsIncorrectIPv4Address {
            get {
                return ResourceManager.GetString("Error_FieldContainsIncorrectIPv4Address", resourceCulture);
            }
        }
        
        internal static string Error_FieldMayContainOnlyCurrencyCode {
            get {
                return ResourceManager.GetString("Error_FieldMayContainOnlyCurrencyCode", resourceCulture);
            }
        }
    }
}
