version: "3.8"

services:
  api:
    container_name: visit-api-dev
    restart: always
    build:
      context: ./../../../
      dockerfile: Vizit.Api/devops/dev/Dockerfile
      args:
        BUILD_COMMAND: build
    environment:
      - ConnectionStrings__ViberBotConnection=${VIBERBOT_CONNECTION_STRING}
      - ConnectionStrings__NkConnection=${NK_CONNECTION_STRING}
      - ConnectionStrings__NkMobileConnection=${NK_MOBILE_CONNECTION_STRING}
      - ConnectionStrings__KievConnection=${KIEV_CONNECTION_STRING}
      - ConnectionStrings__KievMobileConnection=${NK_MOBILE_CONNECTION_STRING}
      - ConnectionStrings__ZpConnection=${ZP_CONNECTION_STRING}
      - ConnectionStrings__ZpMobileConnection=${ZP_MOBILE_CONNECTION_STRING}
      - ConnectionStrings__DnpConnection=${DNP_CONNECTION_STRING}
      - ConnectionStrings__DnpMobileConnection=${DNP_MOBILE_CONNECTION_STRING}
      - ConnectionStrings__KrRgConnection=${KRG_CONNECTION_STRING}
      - ConnectionStrings__KrRgMobileConnection=${KRG_MOBILE_CONNECTION_STRING}
    volumes:
      - ./../../../Vizit.Api/wwwroot:/app/wwwroot
    ports:
      - 5031:80
