apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.images.api.serviceName }}
spec:
  type: ClusterIP
  selector: 
    app: {{ .Values.images.api.deploymentSelector }}
  ports:
    - port: 80
      protocol: TCP
