apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.images.web.deploymentName }}
  labels:
    app: {{ .Values.images.web.name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.images.web.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.images.web.name }}
    spec:
      containers:
      - name: {{ .Values.images.api.name }}
        image: {{ .Values.image.registry }}/{{ .Values.images.web.name }}:{{ .Values.images.web.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: PROJECT_DIR
          value: "OffLogs.Api"
        ports:
        - containerPort: 80
      restartPolicy: Always
      imagePullSecrets:
      - name: {{ .Values.image.secrets }}
