apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.images.web.deploymentName }}
  labels:
    app: {{ .Values.images.web.deploymentSelector }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.images.web.deploymentSelector }}
  template:
    metadata:
      labels:
        app: {{ .Values.images.web.deploymentSelector }}
    spec:
      restartPolicy: Always
      containers:
      - name: {{ .Values.images.api.name }}
        image: {{ .Values.image.registry }}/{{ .Values.images.web.name }}:{{ .Values.images.web.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: {{ .Values.image.secrets }}
