version: "3.8"

services:
  api:
    container_name: offlogs-api-production
    restart: always
    build:
      context: ./../../../
      dockerfile: devops/prod/main/Api/Dockerfile
      args:
        BUILD_COMMAND: build
    environment:
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
      - App__Auth__SymmetricSecurityKey=${JWT_USER_KEY}
      - App__Application__SymmetricSecurityKey=${JWT_APPLICATION_KEY}
      - Kafka__Servers=${KAFKA_SERVERS}
      - Kafka__ProducerId=${KAFKA_PRODUCER_ID}
      - Kafka__Topic_Logs=${KAFKA_TOPIC_LOGS}
      - Kafka__Topic_Notification=${KAFKA_TOPIC_NOTIFICATION}
      - Kafka__ConsumerClientId=${KAFKA_CONSUMER_CLIENT_ID}
      - Smtp__UserName=${SMTP_USERNAME}
      - Smtp__Password=${SMTP_PASSWORD}
    ports:
      - 5051:80
  worker:
    container_name: offlogs-worker-production
    restart: always
    build:
      context: ./../../../
      dockerfile: devops/prod/main/Worker/Dockerfile
      args:
        BUILD_COMMAND: build
    environment:
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
      - App__Auth__SymmetricSecurityKey=${JWT_USER_KEY}
      - App__Application__SymmetricSecurityKey=${JWT_APPLICATION_KEY}
      - Kafka__Servers=${KAFKA_SERVERS}
      - Kafka__ProducerId=${KAFKA_PRODUCER_ID}
      - Kafka__Topic__Logs=${KAFKA_TOPIC_LOGS}
      - Kafka__Topic__Notification=${KAFKA_TOPIC_NOTIFICATION}
      - Kafka__ConsumerClientId=${KAFKA_CONSUMER_CLIENT_ID}
      - Smtp__UserName=${SMTP_USERNAME}
      - Smtp__Password=${SMTP_PASSWORD}
    depends_on:
      - api
  web:
    container_name: offlogs-web-production
    restart: always
    build:
      context: ./../../../
      dockerfile: devops/prod/main/Web/Dockerfile
      args:
        BUILD_COMMAND: build
    ports:
      - 6018:80
    depends_on:
      - api