apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.images.frontApi.deploymentName }}
  labels:
    app: {{ .Values.images.frontApi.deploymentName }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.images.frontApi.deploymentName }}
  template:
    metadata:
      labels:
        app: {{ .Values.images.frontApi.deploymentName }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Values.images.frontApi.name }}
          image: {{ .Values.image.registry }}/{{ .Values.images.frontApi.name }}:{{ .Values.images.frontApi.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PROJECT_DIR
              value: "OffLogs.Api.Frontend"
            {{- include "helpers.pods.env-variables" . | indent 12 }}
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: {{ .Values.image.secrets }}
