apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.images.frontApi.deploymentName }}
  labels:
    app: {{ .Values.images.frontApi.name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.images.frontApi.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.images.frontApi.name }}
    spec:
      containers:
      - name: {{ .Values.images.frontApi.name }}
#        image: {{ .Values.image.registry }}/{{ .Values.images.frontApi.name }}:{{ .Values.images.frontApi.tag }}
        image: cloudnativelabs/whats-my-ip:latest
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: PROJECT_DIR
          value: "OffLogs.Api.Frontend"
        ports:
        - containerPort: 80
      restartPolicy: Always
      imagePullSecrets:
      - name: {{ .Values.image.secrets }}
