---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.images.frontApi.ingressName }}
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - site-api.offlogs.com
      secretName: site-api-offlogs-com-tls-2-secret
  rules:
    - host: site-api.offlogs.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ .Values.images.frontApi.serviceName }}
                port:
                  number: 80
