apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.images.frontApi.serviceName }}
spec:
  type: ClusterIP
  selector: 
    app: {{ .Values.images.frontApi.name }}
  ports:
    - port: 80
      protocol: TCP
