pipeline {
    agent {
        dockerfile true
        dir 'devops/test'
        args '--privileged'
        reuseNode true
    }
    
    options { 
        disableConcurrentBuilds() 
        gitlabBuilds(builds: ['prepairing', 'apply_migrations', 'build', 'test'])
    }
    
    triggers {
        gitlab(triggerOnPush: true, triggerOnMergeRequest: true, branchFilterType: 'All')
    }
    
    environment {
        // Postgres
        POSTGRES_CONNECTION_RETRIES = 5
        POSTGRES_USER = "postgres"
        POSTGRES_PASSWORD = "postgres"
        POSTGRES_DATABASE = "template1"
        
        // Zookeeper
        ZOOKEEPER_CLIENT_PORT = 2181
        ZOOKEEPER_TICK_TIME = 2000
        
        // Kafka
        KAFKA_HOME = "./devops/common/binable/kafka"
        KAFKA_BROKER_ID = 1
        KAFKA_ZOOKEEPER_CONNECT = "localhost:2181"
        KAFKA_LISTENERS = "INSIDE://:9092,OUTSIDE://:9094"
        KAFKA_ADVERTISED_LISTENERS = "INSIDE://:9092,OUTSIDE://localhost:9094"
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP = "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
        KAFKA_INTER_BROKER_LISTENER_NAME = "INSIDE"
        
        // OffLogs
        ConnectionStrings__DefaultConnection = "User ID=postgres;Password=postgres;Host=localhost;Port=5432;Database=postgres;Pooling=true;"
        Kafka__Servers = "localhost:9094"
        Hibernate__IsShowSql = "false"
        
        PATH = "$PATH:$KAFKA_HOME/bin"
    }
    
    stages {
        stage('System Info') {
            steps {
                echo 'Current user $USER'
                sh 'pwd'
            }
        }
        
        stage('Init Zookeeper') {
            steps {
                updateGitlabCommitStatus name: 'prepairing', state: 'running'
                
                sh './devops/common/zookeeper/boot.sh &'
                sh 'until nc -z localhost 2181; do sleep 1; done'
                echo "Zookeeper is started"
            }
        }
        
        stage('Init Kafka') {
            steps {
                sh './devops/common/kafka/boot.sh &'
                sh 'until nc -z localhost 9094; do sleep 1; done'
                echo "Kafka is started"
            }
        }
        
        stage('Init PostgreSQL') {
            steps {
                sh 'pg_ctlcluster 12 main start'
                sh 'netstat -tulpn | grep LISTEN'
                sh 'pg_isready'
                sh 'sudo -u postgres psql -c "ALTER USER postgres PASSWORD \'postgres\';"'
                sh 'PGPASSWORD=postgres psql -h localhost --username=$POSTGRES_USER --dbname=$POSTGRES_DATABASE -c "select 1"'
                echo 'Postgre SQL is started'
                
                updateGitlabCommitStatus name: 'prepairing', state: 'success'
            }
        }
        
        stage('Build') {
            steps {
                updateGitlabCommitStatus name: 'build', state: 'running'
                sh 'dotnet build'
                updateGitlabCommitStatus name: 'build', state: 'success'
            }
        }
        
        stage('Apply Migration') {
            steps {
                updateGitlabCommitStatus name: 'apply_migrations', state: 'success'
            
                echo 'Apply migrations'
                sh 'dotnet run --project="./OffLogs.Migrations/OffLogs.Migrations.csproj"'
                
                updateGitlabCommitStatus name: 'apply_migrations', state: 'success'
            }
        }
        
        stage('Unit Tests') {
            steps {
                updateGitlabCommitStatus name: 'test', state: 'running'
                sh 'dotnet test --logger trx --results-directory /tmp/test ./OffLogs.Api.Tests.Unit'
                sh 'dotnet test --logger trx --results-directory /tmp/test ./OffLogs.Business.Common.Tests.Unit'
            }
        }
        
        stage('Integration Tests') {
            steps {
                sh 'dotnet test --logger trx --results-directory /tmp/test ./OffLogs.Api.Tests.Integration'
            }
        }
        
    }
    
    post {
        success {
            updateGitlabCommitStatus name: 'test', state: 'success'
        }
        
        failure {
            updateGitlabCommitStatus name: 'test', state: 'failed'
        }
        
        aborted {
            updateGitlabCommitStatus name: 'test', state: 'canceled'
        }
        
        unsuccessful {
            updateGitlabCommitStatus name: 'test', state: 'canceled'
        }
    }
}
