version: "3.8"

services:
  api-frontend:
    container_name: offlogs-api-frontend-production
    restart: always
    build:
      context: ./../../
      dockerfile: prod/frontend/Dockerfile
      args:
        BUILD_COMMAND: build
    environment:
      - App__Auth__SymmetricSecurityKey=${JWT_USER_KEY}
      - App__Application__SymmetricSecurityKey=${JWT_APPLICATION_KEY}
      - Kafka_Servers=${KAFKA_SERVERS}
      - Kafka_ProducerId=${KAFKA_PRODUCER_ID}
      - Kafka_Topic_Logs=${KAFKA_TOPIC_LOGS}
      - Kafka_Topic_Notification=${KAFKA_TOPIC_NOTIFICATION}
      - Kafka_ConsumerClientId=${KAFKA_CONSUMER_CLIENT_ID}
    ports:
      - 6033:80