# Default values for publish.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: docker.subs.itproject.club
  pullPolicy: Always # Never - Use local registry, Always - Use other registries
  secrets: dockersecret

images:
  frontApi:
    name: offlogs-main-production
    tag: latest
    deploymentName: offlogs-api-production-deployment
    serviceName: offlogs-api-production-service
    ingressName: offlogs-api-production-ingress
  api:
    name: offlogs-main-production
    tag: latest
    deploymentName: offlogs-front-api-production-deployment
    serviceName: offlogs-front-api-production-service
    ingressName: offlogs-front-api-production-ingress
  web:
    name: offlogs-web-production
    tag: latest
    deploymentName: offlogs-web-production-deployment
    serviceName: offlogs-web-production-service
    ingressName: offlogs-web-production-ingress
  worker:
    name: offlogs-main-production
    tag: latest
    deploymentName: offlogs-worker-production-deployment
    serviceName: offlogs-worker-production-service
    ingressName: offlogs-worker-production-ingress
    
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
