# Default values for publish.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: docker.subs.itproject.club
  pullPolicy: Always # Never - Use local registry, Always - Use other registries
  secrets: dockersecret

images:
  frontApi:
    name: offlogs-main-production
    tag: latest
    deploymentName: offlogs-front-api-production-deployment
    deploymentSelector: offlogs-front-api-production-deployment-selector
    serviceName: offlogs-front-api-production-service
    ingressName: offlogs-front-api-production-ingress
  api:
    name: offlogs-main-production
    tag: latest
    deploymentName: offlogs-api-production-deployment
    deploymentSelector: offlogs-api-production-deployment-selector
    serviceName: offlogs-api-production-service
    ingressName: offlogs-api-production-ingress
  web:
    name: offlogs-web-production
    tag: latest
    deploymentName: offlogs-web-production-deployment
    deploymentSelector: offlogs-web-production-deployment-selector
    serviceName: offlogs-web-production-service
    ingressName: offlogs-web-production-ingress
  worker:
    name: offlogs-main-production
    tag: latest
    deploymentName: offlogs-worker-production-deployment
    deploymentSelector: offlogs-worker-production-deployment-selector
    serviceName: offlogs-worker-production-service
    ingressName: offlogs-worker-production-ingress
  migration:
    name: offlogs-main-production
    tag: latest
    deploymentName: offlogs-migration-production-deployment
    deploymentSelector: offlogs-migration-production-deployment-selector
    serviceName: offlogs-migration-production-service
    ingressName: offlogs-migration-production-ingress

pods:
  env: 
    Kafka__Servers: 192.168.110.6:29092,192.168.110.6:29093
    Kafka__ProducerId: offlogs-reducer-
    Kafka__ConsumerClientId: offlogs-consumer-
    Kafka__Topic__Logs: offlogs-production-logs
    Kafka__Topic__Notifications: offlogs-notification-logs
    Smtp__Server: smtp-pulse.com
    Smtp__From__Name: OffLogs
    Smtp__From__Email: support@offlogs.com
    Smtp__Port: 2525
    Smtp__EnableSsl: true

    ConnectionStrings__DefaultConnection: User ID=;Password=;Host=192.168.110.6;Port=5432;Database=offlogs;Pooling=true;
    Smtp__UserName: ''
    Smtp__Password: ''
    App__Auth__SymmetricSecurityKey: ''
    App__Application__SymmetricSecurityKey: ''
    ReCaptcha__Secret: ''

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
