version: "3.8"

services:
  api:
    container_name: offlogs-api-production
    restart: always
    build:
      context: ./../../../
      dockerfile: devops/dev/Api/Dockerfile
      args:
        BUILD_COMMAND: build
    environment:
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
    volumes:
      - ./../../../Vizit.Api/wwwroot:/app/wwwroot
    ports:
      - 5031:80
    depends_on:
      - migrations
  migrations:
    container_name: offlogs-migrations-production
    restart: always
    build:
      context: ./../../../
      dockerfile: devops/dev/Migrations/Dockerfile
      args:
        BUILD_COMMAND: build
    environment:
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
    volumes:
      - ./../../../Vizit.Api/wwwroot:/app/wwwroot
    ports:
      - 5031:80