version: "3.8"

services:
  api:
    container_name: offlogs-api-production
    restart: always
    build:
      context: ./../../
      dockerfile: devops/prod/Api/Dockerfile
      args:
        BUILD_COMMAND: build
    environment:
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
      - App__Auth__SymmetricSecurityKey=${JWT_USER_KEY}
      - App__Application__SymmetricSecurityKey=${JWT_APPLICATION_KEY}
    ports:
      - 5051:80
  api-frontend:
    container_name: offlogs-api-frontend-production
    restart: always
    build:
      context: ./../../
      dockerfile: devops/prod/Api.Frontend/Dockerfile
      args:
        BUILD_COMMAND: build
    environment:
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
      - App__Auth__SymmetricSecurityKey=${JWT_USER_KEY}
      - App__Application__SymmetricSecurityKey=${JWT_APPLICATION_KEY}
    ports:
      - 6033:80
    depends_on: api
  worker:
    container_name: offlogs-worker-production
    restart: always
    build:
      context: ./../../
      dockerfile: devops/prod/Worker/Dockerfile
      args:
        BUILD_COMMAND: build
    environment:
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
      - App__Auth__SymmetricSecurityKey=${JWT_USER_KEY}
      - App__Application__SymmetricSecurityKey=${JWT_APPLICATION_KEY}
    depends_on: api
  web:
    container_name: offlogs-web-production
    restart: always
    build:
      context: ./../../
      dockerfile: devops/prod/Web/Dockerfile
      args:
        BUILD_COMMAND: build
    ports:
      - 6018:80
  depends_on: api