version: "3.8"

volumes:
  common: {}
  

services:
  mssql:
    container_name: offlogs-local-database
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      - SA_PASSWORD=${MSSQL_PASSWORD}
      - ACCEPT_EULA=Y
    ports:
      - 1448:1433
    volumes:
      - common:/var/opt/mssql