version: "3.8"

volumes:
  postgre-volume: {}
  

services:
  postgres:
    container_name: offlogs-local-postgres
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgre-volume:/var/lib/postgresql/data