//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OffLogs.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DocResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OffLogs.Web.Resources.DocResources", typeof(DocResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Net Client.
        /// </summary>
        internal static string DocumentTitle_DotNet {
            get {
                return ResourceManager.GetString("DocumentTitle_DotNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Net Core Extension.
        /// </summary>
        internal static string DocumentTitle_DotNetCore {
            get {
                return ResourceManager.GetString("DocumentTitle_DotNetCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Level.
        /// </summary>
        internal static string DocumentTitle_LogLevel {
            get {
                return ResourceManager.GetString("DocumentTitle_LogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest API.
        /// </summary>
        internal static string DocumentTitle_RestApi {
            get {
                return ResourceManager.GetString("DocumentTitle_RestApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serilog Extension.
        /// </summary>
        internal static string DocumentTitle_SerilogExtension {
            get {
                return ResourceManager.GetString("DocumentTitle_SerilogExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API.
        /// </summary>
        internal static string MenuItem_Api {
            get {
                return ResourceManager.GetString("MenuItem_Api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Info.
        /// </summary>
        internal static string MenuItem_Common {
            get {
                return ResourceManager.GetString("MenuItem_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Resource.
        /// </summary>
        internal static string MenuItem_MessageResource {
            get {
                return ResourceManager.GetString("MenuItem_MessageResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OffLogs Documentation.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
    }
}
