//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OffLogs.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LandingPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LandingPageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OffLogs.Web.Resources.LandingPageResources", typeof(LandingPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        internal static string Documentation_Title {
            get {
                return ResourceManager.GetString("Documentation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error. Please contact to the support :(.
        /// </summary>
        internal static string Error_500 {
            get {
                return ResourceManager.GetString("Error_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Main_About {
            get {
                return ResourceManager.GetString("Main_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        internal static string Main_Desc {
            get {
                return ResourceManager.GetString("Main_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /// - Нет необходимости в ручном режиме отслеживать отладочную информацию от ваших ресурсов, 
        ///особенно если они расположены на различных серверах
        /// - Гибкая система оповещения при получении той или иной отладочной информации
        /// - Просмотр развернутой статистики
        /// - Удобный просмотр и фильтрация логов
        ///        .
        /// </summary>
        internal static string Main_Features_Desc {
            get {
                return ResourceManager.GetString("Main_Features_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        internal static string Main_Features_Title {
            get {
                return ResourceManager.GetString("Main_Features_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Наиболее частый случай когда OffLogs может вам помочь:
        ///
        ///1. Предположим, у вас есть один или несколько сайтов. Эти сайты расположены на различных серверах
        ///2. Вы используя один из наших клиентов или создаете свой логгер для отправки логов в наше API.
        ///   (Как это сделать можете прочитать [тут](/documentation/api/2_1_rest_api))
        ///3. После чего ваши сайты, в процессе работы, будут генерировать отладочную информацию которая будет получена и зашифрована нашим сервисом.
        ///4. Все :) Теперь вы можете просмотреть всю отл [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Main_HowItWorks_Desc {
            get {
                return ResourceManager.GetString("Main_HowItWorks_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How it works?.
        /// </summary>
        internal static string Main_HowItWorks_Title {
            get {
                return ResourceManager.GetString("Main_HowItWorks_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the OffLogs project.
        /// </summary>
        internal static string Main_Title {
            get {
                return ResourceManager.GetString("Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Menu_Dashboard {
            get {
                return ResourceManager.GetString("Menu_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Menu_Login {
            get {
                return ResourceManager.GetString("Menu_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string Menu_SignUp {
            get {
                return ResourceManager.GetString("Menu_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///If you found any bug please check or add your bug to our [bug tracker](https://gitlab.com/offlogs-public/main/-/issues)
        ///for already reported and discussed bugs and feature requests.
        ///        .
        /// </summary>
        internal static string Support_Desc_BugTracking {
            get {
                return ResourceManager.GetString("Support_Desc_BugTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///To get additional information on how to integrate and working with OffLogs, our [Wiki](/documentation/common/1_1_common) will help.
        ///        .
        /// </summary>
        internal static string Support_Desc_Documentation {
            get {
                return ResourceManager.GetString("Support_Desc_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///If you have any questions please send us an email at **support@offlogs.com**
        ///        .
        /// </summary>
        internal static string Support_Desc_Email {
            get {
                return ResourceManager.GetString("Support_Desc_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            For issues concerning the software itself, there are several ways to get help on questions about OffLogs. Please choose from the following:
        ///        .
        /// </summary>
        internal static string Support_Header {
            get {
                return ResourceManager.GetString("Support_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need help?.
        /// </summary>
        internal static string Support_Title {
            get {
                return ResourceManager.GetString("Support_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found a bug?.
        /// </summary>
        internal static string Support_Title_BugTracking {
            get {
                return ResourceManager.GetString("Support_Title_BugTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation Wiki.
        /// </summary>
        internal static string Support_Title_Documentation {
            get {
                return ResourceManager.GetString("Support_Title_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact info.
        /// </summary>
        internal static string Support_Title_Email {
            get {
                return ResourceManager.GetString("Support_Title_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address has been successfully verified!.
        /// </summary>
        internal static string User_EmailSuccessfullyVerified {
            get {
                return ResourceManager.GetString("User_EmailSuccessfullyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email verification.
        /// </summary>
        internal static string User_EmailVerification {
            get {
                return ResourceManager.GetString("User_EmailVerification", resourceCulture);
            }
        }
    }
}
