//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OffLogs.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NotificationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OffLogs.Web.Resources.NotificationResources", typeof(NotificationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new rule.
        /// </summary>
        internal static string AddNewRule {
            get {
                return ResourceManager.GetString("AddNewRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new template.
        /// </summary>
        internal static string AddNewTemplate {
            get {
                return ResourceManager.GetString("AddNewTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select field.
        /// </summary>
        internal static string Condition_FieldType {
            get {
                return ResourceManager.GetString("Condition_FieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this rule?.
        /// </summary>
        internal static string Confirmation_AreSureToDeleteRule {
            get {
                return ResourceManager.GetString("Confirmation_AreSureToDeleteRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this template?.
        /// </summary>
        internal static string Confirmation_AreSureToDeleteTemplate {
            get {
                return ResourceManager.GetString("Confirmation_AreSureToDeleteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit rule.
        /// </summary>
        internal static string EditRule {
            get {
                return ResourceManager.GetString("EditRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit template.
        /// </summary>
        internal static string EditTemplate {
            get {
                return ResourceManager.GetString("EditTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new rue.
        /// </summary>
        internal static string MenuItem_AddRule {
            get {
                return ResourceManager.GetString("MenuItem_AddRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new template.
        /// </summary>
        internal static string MenuItem_AddTemplate {
            get {
                return ResourceManager.GetString("MenuItem_AddTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string MenuItem_Delete {
            get {
                return ResourceManager.GetString("MenuItem_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit rue.
        /// </summary>
        internal static string MenuItem_EditRule {
            get {
                return ResourceManager.GetString("MenuItem_EditRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit template.
        /// </summary>
        internal static string MenuItem_EditTemplate {
            get {
                return ResourceManager.GetString("MenuItem_EditTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message templates.
        /// </summary>
        internal static string MenuItem_MessageTemplates {
            get {
                return ResourceManager.GetString("MenuItem_MessageTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification rules.
        /// </summary>
        internal static string MenuItem_Rules {
            get {
                return ResourceManager.GetString("MenuItem_Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New message template was added.
        /// </summary>
        internal static string MessageTemplate_Added {
            get {
                return ResourceManager.GetString("MessageTemplate_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message body.
        /// </summary>
        internal static string MessageTemplate_Body {
            get {
                return ResourceManager.GetString("MessageTemplate_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter message body.
        /// </summary>
        internal static string MessageTemplate_BodyPlaceholder {
            get {
                return ResourceManager.GetString("MessageTemplate_BodyPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not delete this template. Perhaps it already assigned to the notification rule.
        /// </summary>
        internal static string MessageTemplate_CantDelete {
            get {
                return ResourceManager.GetString("MessageTemplate_CantDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message template was deleted.
        /// </summary>
        internal static string MessageTemplate_Deleted {
            get {
                return ResourceManager.GetString("MessageTemplate_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New message template was saved.
        /// </summary>
        internal static string MessageTemplate_Saved {
            get {
                return ResourceManager.GetString("MessageTemplate_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string MessageTemplate_Subject {
            get {
                return ResourceManager.GetString("MessageTemplate_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add condition.
        /// </summary>
        internal static string Rules_AddCondition {
            get {
                return ResourceManager.GetString("Rules_AddCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New rule was added.
        /// </summary>
        internal static string Rules_Added {
            get {
                return ResourceManager.GetString("Rules_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string Rules_Application {
            get {
                return ResourceManager.GetString("Rules_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition value.
        /// </summary>
        internal static string Rules_ConditionValue {
            get {
                return ResourceManager.GetString("Rules_ConditionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to combine conditions.
        /// </summary>
        internal static string Rules_HowToCombineConditions {
            get {
                return ResourceManager.GetString("Rules_HowToCombineConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message template.
        /// </summary>
        internal static string Rules_MessageTemplate {
            get {
                return ResourceManager.GetString("Rules_MessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period (sec.).
        /// </summary>
        internal static string Rules_Period {
            get {
                return ResourceManager.GetString("Rules_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Rules_RuleTitle {
            get {
                return ResourceManager.GetString("Rules_RuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule was saved.
        /// </summary>
        internal static string Rules_Saved {
            get {
                return ResourceManager.GetString("Rules_Saved", resourceCulture);
            }
        }
    }
}
